
db: 'sqlite:////Users/nathan/sources/coinbot/coinbot.db'

exchanges:
  bittrex:
    apiKey: your-api-key-here
    secret: your-secret-here

slack:
  key: xoxp-your-slack-key-here
  token: your-slack-api-token-here
  channel: coinbot-dev
  username: dev
  emojis:
    default: ':dolphin:'
    cron: 'dolphin'

account: devtesting

seed: 42

spreadsheet:
  url: https://something-google.com/here
  secret: your-spreadsheet-handler-secret-here

backtesting:
  trials: 100
  trial_days: 10
  threads: 1
